trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docs/*

pool:
  vmImage: windows-latest

steps:

- task: DocFxTask@0
  inputs:
    solution: 'docs'

- task: PublishBuildArtifacts@1
  displayName: Load to artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/docs/_site'
    ArtifactName: 'style-guide-drop'
    publishLocation: 'Container'

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'docs/_site'
    azureSubscription: 'Azure.CloudAwesomeXyz.Blob'
    Destination: 'AzureBlob'
    storage: 'cloudawesomexyz'
    ContainerName: '$web'
    BlobPrefix: 'style-guide'
