trigger:
  branches:
    include:
      - main
  paths:
    include:
      - docs/*

pool:
  vmImage: windows-latest

steps:

- task: DocFxTask@0
  displayName: Build Documentation
  inputs:
    solution: 'docs'

- task: AzureFileCopy@4
  displayName: Publish to Azure Blob
  inputs:
    SourcePath: 'docs/_site/*'
    azureSubscription: 'Azure.CloudAwesomeXyz.Blob'
    Destination: 'AzureBlob'
    storage: 'cloudawesomexyz'
    ContainerName: '$web'
    BlobPrefix: 'style-guide'
    AdditionalArgumentsForBlobCopy: '--recursive'
